name: MovieBox Scraper Bot
on:
  schedule:
    - cron: '0 */6 * * *' # Har 6 ghante chalega
  workflow_dispatch: # Manual button

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Libraries
        run: pip install requests beautifulsoup4 google-api-python-client google-auth
        
      - name: Run Scraper Script
        env:
          GDRIVE_API_KEY: ${{ secrets.GDRIVE_API_KEY }}
        run: python scraper.py
        
      - name: Save History to GitHub
        run: |
          # Git configuration
          git config --global user.name 'KroldBot'
          git config --global user.email 'bot@krold.it'
          
          # History file ensure karo
          touch history.txt
          git add history.txt
          
          # Check karo agar change hua hai tabhi commit karo
          if git diff --staged --quiet; then
            echo "Koi change nahi hua history mein. Skipping commit."
          else
            git commit -m "Update video history"
            git push
          fi
