name: Krold Mega Bot (Cloud)
on:
  schedule:
    - cron: '0 */4 * * *' # Har 4 ghante chalega
  workflow_dispatch:      # Manual button bhi rahega

jobs:
  run-cloud-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Libraries
        run: pip install requests beautifulsoup4 google-api-python-client google-auth-oauthlib
        
      - name: Run The Bot
        env:
          GDRIVE_API_KEY: ${{ secrets.GDRIVE_API_KEY }}
          YT_TOKEN_BASE64: ${{ secrets.YT_TOKEN_BASE64 }}
        run: python mega_bot.py
        
      - name: Save History
        run: |
          git config --global user.name 'KroldBot'
          git config --global user.email 'bot@krold.it'
          git add history.txt
          git commit -m "Processed new video" || exit 0
          git push
